### ISSUE TITLE
User Story 50 : Metier + Acces aux données pour ajouter un client

### ISSUE THREAD

**Issue by badich** [DTAFormation/vente-en-ligne-admin#1]
Objectif:
-Créer l’accès a la base de données pour voir un client.

Validation:
- Voir apparaître dans la base de données le client.

**Comment by badich** [comment]
Créer l’accès a la base de données pour voir un client.

**Comment by roddet** [comment]
Pourrais-tu mettre les critères d'acceptation dans la description ?

**Comment by badich** [comment]
Critère d'acception spécifique a cette tâche:
 - Voir apparaître dans la base de données le client,
 - pas de doublon : login
